version: '3'
services:
  home:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ../../mounts/home/home1/home-server/build:/html
    depends_on:
      - api-server
  api-server:
    build: ./api
    environment:
      - PORT=8080
      - WEBPOWERBAR0_PW=webpower1Man
      - WEBPOWERBAR1_PW=webpower1Man
    ports:
      - "8082:8080"
    volumes:
      - ../../mounts/home/home1/api-server:/usr/src/app
