version: '3'
services:
  do:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ../../../mounts/do:/html
    depends_on:
      - tinaandcarlton2weddinginvite
      - tinaandcarlton3wedding
